export const GameState = {
  playerId: null,
  roomId: null,
  localPlayer: null,
  localDrone: null,
  allGltfs: {},
  mapRootRef: null,
  collisionRootRef: null,
  explosionFX: null,
  collisionWorld: null,
  sceneMgr: null,
  camMgr: null,
  hud: null,
  audio: null,
  mode: 'walk',
  camYaw: 0,
  inGame: false,
  ready: false,
  lastCrashProcessed: false,
};