export const SERVER_CONFIG = {
  PORT: process.env.PORT || 8080,
  SNAPSHOT_HZ: 20,
  MAX_PACKETS_PER_SEC: 90,
  MAX_VALIDATION_FAILS: 200,
  ENTER_DRONE_MAX_DIST: 15,
  PLAYER_TIMEOUT_MS: 5000,
  RATE_WINDOW_MS: 1000,
  MAX_PLAYERS_PER_ROOM: 10,
  CLEANUP_INTERVAL_MS: 1000,
};